config/routes.rb
Magyarul::Application.routes.draw do

  root :to => "gyulas#index"
  post 'gyulas/speak' => 'gyulas#speak'
  get 'gyulas/index' => 'gyulas#index'

  

end

app/models/gyula.rb
class Gyula < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gyulas_controller.rb
class GyulasController < ApplicationController
  require 'uri'
  # GET /gyulas
  # GET /gyulas.json
  def index
    @gyulas = Gyula.all
  end

  def speak
    if params[:q].present?
      googleuri=CGI.escape(URI.encode('http://translate.google.com/translate_tts?tl='+params[:language]+'&q='+params[:q]))
      Curl::Easy.http_get('http://api.wizz.cc/?sn=001D921058F8&token=4f4a80beb5a26185b28f6c773a862fcc&server=pixel&urlList='+googleuri)
    end
    render nothing: true
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyulas_helper.rb
module GyulasHelper
end

app/views/gyulas/_form.html.erb
<%= form_for(@gyula) do |f| %>
  <% if @gyula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gyula.errors.count, "error") %> prohibited this gyula from being saved:</h2>

      <ul>
      <% @gyula.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gyulas/edit.html.erb
<h1>Editing gyula</h1>

<%= render 'form' %>

<%= link_to 'Show', @gyula %> |
<%= link_to 'Back', gyulas_path %>

app/views/gyulas/index.html.erb
<br><br><br>

<%= form_tag("/gyulas/speak", method: "post", remote: true) do %>
  <%= text_field_tag(:q) %><br>
  <%= select_tag(:language, options_for_select([['English', 'en'], ['Hungarian', 'hu']])) %>
  <br><br>
  <%= submit_tag("Talk!") %>
  
<% end %>

app/views/gyulas/new.html.erb
<h1>New gyula</h1>

<%= render 'form' %>

<%= link_to 'Back', gyulas_path %>

app/views/gyulas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gyula_path(@gyula) %> |
<%= link_to 'Back', gyulas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magyarul</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>